### ISSUE TITLE
textdraw (global, player), CreateMenu and player pos

### ISSUE THREAD

**Issue by Laronic** [damospiderman/samp.js#30]
I've added some comments in the test code below explaining whats happening. Using `samp.js v0.1.9.1` on `win8.1`
- `TextDrawCreate`, `CreatePlayerTextDraw` and `CreateMenu` don't return any id, just `undefined`
- `player.pos` (`SetPlayerPos`) teleport me to incorrect coords
- `player.pos` (`GetPlayerPos`) returns incorrect coords

_Test code:_

``` javascript
include('js/include/a_samp.inc.js');
include('js/include/a_players.inc.js');
include('js/include/a_vehicles.inc.js');

$server.on("GameModeInit", function()
{
    print("Creating global-textdraw: "+ TextDrawCreate(0.0, 0.0, 'Hello World!')); //Creating global-textdraw: undefined
    print("Creating player-textdraw: "+ CreatePlayerTextDraw(0, 0.0, 0.0, 'Hello World!')); //Creating player-textdraw: undefined
    print("Creating menu: "+ CreateMenu('Hello World!', 0, 0.0, 0.0, 0.0, 0.0)); //Creating textdraw: undefined

    AddPlayerClass(0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0);
    return 1;
});

$server.on("PlayerCommandText", function(player, cmdtext)
{
    var args = cmdtext.split(' ');
    let cmd = args.shift();

    if(cmd == '/sf')
    {
        print('Teleporting to San Fierro');
        player.pos = [-2080.44, 296.51, 69.80, 0.0]; //Position changes to: 69.8000, 69.8000, 69.8000, 0.0000 (SA-MP /rs)

        let pos = player.pos;
        print('New pos: '+ JSON.stringify(pos)); //PËQXžd

        print(`New pos: ${pos.x}, ${pos.y}, ${pos.z}, ${pos.a}`); //New pos: -30.913068771362305, -13.963459014892578, 3.109395980834961, 209.77845764160156
        return 1;
    }
    return 0;
});
```

_log:_

```
[04:48:42] Creating global-textdraw: undefined
[04:48:42] Creating player-textdraw: undefined
[04:48:42] Creating menu: undefined
[04:49:35] Teleporting to San Fierro
[04:49:35] PËQXžd
[04:49:35] New pos: -30.913068771362305, -13.963459014892578, 3.109395980834961, 209.77845764160156
```

By the way, nice work! I'm lovin' it!

**Comment by damopewpew** [comment]
Hi Laronic,

Thanks for the bug report.

Those issues are now fixed in this release https://github.com/damospiderman/samp.js/releases/tag/v0.1.9.2

The only thing that won't work how you expect is getting the players position straight after you set it. This isn't a samp.js issue but a samp issue, its basically because the position hasn't been properly set by the time you call the get.

If you do want to get the position straight after you set it the player class has cached values so you can do player._pos which will be the last set/get position.

**Comment by Laronic** [comment]
Thanks!
